import { Anthropic } from "@anthropic-ai/sdk";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import AppConfig from "./config.server";
import systemPrompts from "../prompts/prompts.json";

// ---------------------------------------------------------------------------
// Customer-care knowledge base — auto-generated by the dylan-chat-agent
// Cowork plugin and synced into app/prompts/customer-care.md.
// Loaded once at module initialization and appended to every system prompt.
// ---------------------------------------------------------------------------
const __dirname = path.dirname(fileURLToPath(import.meta.url));
const CUSTOMER_CARE_PATH = path.resolve(__dirname, "../prompts/customer-care.md");

let customerCareKnowledge = "";
try {
  customerCareKnowledge = fs.readFileSync(CUSTOMER_CARE_PATH, "utf8").trim();
  console.log(`Loaded Dylan customer-care knowledge (${customerCareKnowledge.length} chars) from ${CUSTOMER_CARE_PATH}`);
} catch (err) {
  console.warn(`customer-care.md not found at ${CUSTOMER_CARE_PATH} — Dylan will run without it.`);
}

export function createClaudeService(apiKey = process.env.CLAUDE_API_KEY) {
  const anthropic = new Anthropic({ apiKey });

  const streamConversation = async ({
    messages,
    promptType = AppConfig.api.defaultPromptType,
    tools
  }, streamHandlers) => {
    const systemInstruction = getSystemPrompt(promptType);

    const stream = await anthropic.messages.stream({
      model: AppConfig.api.defaultModel,
      max_tokens: AppConfig.api.maxTokens,
      system: systemInstruction,
      messages,
      tools: tools && tools.length > 0 ? tools : undefined
    });

    if (streamHandlers.onText) stream.on('text', streamHandlers.onText);
    if (streamHandlers.onMessage) stream.on('message', streamHandlers.onMessage);
    if (streamHandlers.onContentBlock) stream.on('contentBlock', streamHandlers.onContentBlock);

    const finalMessage = await stream.finalMessage();

    if (streamHandlers.onToolUse && finalMessage.content) {
      for (const content of finalMessage.content) {
        if (content.type === "tool_use") {
          await streamHandlers.onToolUse(content);
        }
      }
    }

    return finalMessage;
  };

  const getSystemPrompt = (promptType) => {
    const base = systemPrompts.systemPrompts[promptType]?.content ||
      systemPrompts.systemPrompts[AppConfig.api.defaultPromptType].content;

    if (!customerCareKnowledge) return base;

    return `${base}\n\n## Customer Care Knowledge\n\n${customerCareKnowledge}`;
  };

  return { streamConversation, getSystemPrompt };
}

export default { createClaudeService };
