import { Anthropic } from "@anthropic-ai/sdk";
import AppConfig from "./config.server";
import systemPrompts from "../prompts/prompts.json";
// Customer-care knowledge — auto-generated by the dylan-chat-agent
// Cowork plugin and synced into app/prompts/customer-care.md.
// Imported with Vite's ?raw suffix so the markdown is bundled into the
// build at compile time; this avoids fs path issues post-build (where
// __dirname would otherwise point inside build/ rather than the source).
import customerCareRaw from "../prompts/customer-care.md?raw";

const KNOWLEDGE = (customerCareRaw || "").trim();
if (KNOWLEDGE) {
  console.log(`Loaded Dylan customer-care knowledge (${KNOWLEDGE.length} chars, bundled).`);
} else {
  console.warn("Dylan customer-care knowledge is empty — Dylan will run without it.");
}

export function createClaudeService(apiKey = process.env.CLAUDE_API_KEY) {
  const anthropic = new Anthropic({ apiKey });

  const streamConversation = async ({
    messages,
    promptType = AppConfig.api.defaultPromptType,
    tools
  }, streamHandlers) => {
    const systemInstruction = getSystemPrompt(promptType);

    const stream = await anthropic.messages.stream({
      model: AppConfig.api.defaultModel,
      max_tokens: AppConfig.api.maxTokens,
      system: systemInstruction,
      messages,
      tools: tools && tools.length > 0 ? tools : undefined
    });

    if (streamHandlers.onText) stream.on('text', streamHandlers.onText);
    if (streamHandlers.onMessage) stream.on('message', streamHandlers.onMessage);
    if (streamHandlers.onContentBlock) stream.on('contentBlock', streamHandlers.onContentBlock);

    const finalMessage = await stream.finalMessage();

    if (streamHandlers.onToolUse && finalMessage.content) {
      for (const content of finalMessage.content) {
        if (content.type === "tool_use") {
          await streamHandlers.onToolUse(content);
        }
      }
    }

    return finalMessage;
  };

  const getSystemPrompt = (promptType) => {
    const base = systemPrompts.systemPrompts[promptType]?.content ||
      systemPrompts.systemPrompts[AppConfig.api.defaultPromptType].content;
    if (!KNOWLEDGE) return base;
    return `${base}\n\n## Customer Care Knowledge\n\n${KNOWLEDGE}`;
  };

  return { streamConversation, getSystemPrompt };
}

export default { createClaudeService };
