# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "721c43603b1c22a576a26810890557ae"
name = "Dylan CS Agent"
application_url = "https://dylan-chat-agent.onrender.com"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-04"

[access_scopes]
scopes = "read_orders,read_product_listings,read_products,read_returns,read_shipping"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [ "https://dylan-chat-agent.onrender.com/auth/callback", "https://barefootincau.myshopify.com/auth/callback" ]

[customer_authentication]
redirect_uris = ["https://dylan-chat-agent.onrender.com/auth/callback", "https://barefootincau.myshopify.com/auth/callback"]
